application: soundcast-app
version: 1
runtime: php
api_version: 1

handlers:

- url: /receiver/index.html
  static_files: app/receiver/index.html
  upload: app/receiver/index\.html
  mime_type: text/html; charset=utf-8

- url: /app/(.+)
  static_files: app/\1
  upload: app/(.*)

skip_files:
  - ^(.*/)?.*node_modules/.*$
  - ^(.*/)?.*bower_components/.*$
  - ^(.*/)?.*.swp
